### ISSUE TITLE
False Positive 

### ISSUE THREAD

**Issue by qwertyva1** [shadowwalker00/Instacart_Alert#4]
After running the script I noticed that when the page reloads after the sleep duration, the script sends a notification that an available time slot has been found. When it really isnt an available time slot.

**Comment by shadowwalker00** [comment]
@qwertyva1  I'm not sure whether I located the bug correctly. Could you post a screenshot of web page when the alert is making so that I could reproduce the error?

**Comment by qwertyva1** [comment]
The error occurs before the no delivery image loads on the checkout page. There roughly a 1-3 second delay before the image appears.

**Comment by shadowwalker00** [comment]
I get it. So a tricky way is to increase the time lapse for waiting the load?

**Comment by shadowwalker00** [comment]
@qwertyva1 I think I fixed the bug you mentioned. After refresh, the page should be waited several  secs to load fully.
